name: Code Coverage and Tests with Pytest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install UV.
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Sync dependencies.
        run: uv sync --all-extras --dev

      - name: Run tests with coverage.
        run: uv run pytest tests

